#!/bin/bash

#
# This script is copied from
# https://github.com/embarkmobile/android-maven-example
# Use it in .travis.yml when testing with Robotium a
# framework which requires virtual devices to run tests.
#

bootanim=""
failcounter=0
until [[ "$bootanim" =~ "stopped" ]]; do
bootanim=`adb -e shell getprop init.svc.bootanim 2>&1`
   echo "$bootanim"
   if [[ "$bootanim" =~ "not found" ]]; then
let "failcounter += 1"
      if [[ $failcounter -gt 3 ]]; then
echo "Failed to start emulator"
        exit 1
      fi
fi
sleep 1
done
echo "Done"